import {
  Pessoa,
  Veiculo,
  Produto,
  OrdemServico,
  Marca,
  Categoria,
  TipoVeiculo,
  User,
  Usuario,
} from '@/types';

export const mockUser: User = {
  id: '1',
  nome: 'João Silva',
  email: 'joao@example.com',
  role: 'admin',
};

export const mockPessoas: Pessoa[] = [
  {
    id: '1',
    nomeCompleto: 'Maria Santos',
    genero: 'F',
    dataNascimento: '1990-05-15',
    tipo: 'Física',
    endereco: {
      logradouro: 'Rua A',
      numero: '123',
      complemento: 'Apto 101',
      bairro: 'Centro',
      cidade: 'São Paulo',
      uf: 'SP',
      pais: 'Brasil',
      cep: '01310-100',
    },
    telefone: '(11) 98765-4321',
    email: 'maria@example.com',
    isFornecedor: true,
    observacao: 'Cliente desde 2020',
    dataCriacao: '2020-01-15',
    dataAtualizacao: '2024-01-15',
  },
  {
    id: '2',
    nomeCompleto: 'Carlos Oliveira',
    genero: 'M',
    dataNascimento: '1985-08-20',
    tipo: 'Física',
    endereco: {
      logradouro: 'Avenida B',
      numero: '456',
      bairro: 'Vila Mariana',
      cidade: 'São Paulo',
      uf: 'SP',
      pais: 'Brasil',
      cep: '04012-000',
    },
    telefone: '(11) 99876-5432',
    email: 'carlos@example.com',
    isFornecedor: false,
    dataCriacao: '2021-03-20',
    dataAtualizacao: '2024-02-10',
  },
];

export const mockVeiculos: Veiculo[] = [
  {
    id: '1',
    placa: 'ABC-1234',
    modelo: 'Corolla',
    ano: 2022,
    cor: 'Prata',
    quilometragem: 25000,
    tipoVeiculo: 'Sedan',
    motorizacao: '2.0',
    numeroChasse: 'JTDKN3AU5L0123456',
    tipoCombustivel: 'Gasolina',
    dataUltimaRevisao: '2024-01-10',
    dataCriacao: '2022-06-15',
    dataAtualizacao: '2024-01-10',
  },
  {
    id: '2',
    placa: 'XYZ-9876',
    modelo: 'Civic',
    ano: 2021,
    cor: 'Preto',
    quilometragem: 35000,
    tipoVeiculo: 'Sedan',
    motorizacao: '1.8',
    numeroChasse: 'JHGCV5F32LM234567',
    tipoCombustivel: 'Gasolina',
    dataUltimaRevisao: '2023-12-20',
    dataCriacao: '2021-09-20',
    dataAtualizacao: '2023-12-20',
  },
];

export const mockProdutos: Produto[] = [
  {
    id: '1',
    titulo: 'Filtro de Óleo',
    descricao: 'Filtro de óleo de alta qualidade',
    codigoSku: 'FO-001',
    marca: 'Bosch',
    categoria: 'Filtros',
    fornecedor: 'Auto Parts Brasil',
    preco: 45.90,
    estoqueAtual: 150,
    tipoItem: 'Produto',
    dataCriacao: '2023-01-10',
    dataAtualizacao: '2024-01-15',
  },
  {
    id: '2',
    titulo: 'Pastilha de Freio',
    descricao: 'Pastilha de freio dianteira',
    codigoSku: 'PF-002',
    marca: 'Fras-le',
    categoria: 'Freios',
    fornecedor: 'Auto Parts Brasil',
    preco: 120.50,
    estoqueAtual: 80,
    tipoItem: 'Produto',
    dataCriacao: '2023-02-15',
    dataAtualizacao: '2024-01-20',
  },
];

export const mockOrdensSevico: OrdemServico[] = [
  {
    id: 'OS-001',
    status: 'Concluída',
    clienteNome: 'Maria Santos',
    clienteCpfCnpj: '123.456.789-10',
    clienteTelefone: '(11) 98765-4321',
    clienteEmail: 'maria@example.com',
    veiculoMarca: 'Toyota',
    veiculoModelo: 'Corolla',
    veiculoAno: 2022,
    veiculoPlaca: 'ABC-1234',
    veiculoCor: 'Prata',
    veiculoQuilometragem: 15000,
    nivelCombustivel: '3/4',
    dataEntrada: '2024-01-10',
    solicitacaoCliente: 'Troca de óleo e filtro',
    diagnostico: 'Veículo em perfeito estado, realizada troca de óleo e filtro conforme solicitado',
    itens: [
      {
        id: '1',
        produtoId: '1',
        quantidade: 1,
        preco: 45.90,
        subtotal: 45.90,
      },
    ],
    valorTotal: 45.90,
    dataAbertura: '2024-01-10',
    dataConclusao: '2024-01-12',
    dataCriacao: '2024-01-10',
    dataAtualizacao: '2024-01-12',
  },
  {
    id: 'OS-002',
    status: 'Em Andamento',
    clienteNome: 'Carlos Oliveira',
    clienteCpfCnpj: '987.654.321-00',
    clienteTelefone: '(11) 99876-5432',
    clienteEmail: 'carlos@example.com',
    veiculoMarca: 'Honda',
    veiculoModelo: 'Civic',
    veiculoAno: 2021,
    veiculoPlaca: 'XYZ-5678',
    veiculoCor: 'Preto',
    veiculoQuilometragem: 28000,
    nivelCombustivel: '1/2',
    dataEntrada: '2024-01-20',
    solicitacaoCliente: 'Revisão completa e alinhamento',
    diagnostico: 'Alinhamento desajustado, realizada revisão completa e alinhamento das rodas',
    itens: [
      {
        id: '1',
        produtoId: '2',
        quantidade: 1,
        preco: 120.50,
        subtotal: 120.50,
      },
    ],
    valorTotal: 120.50,
    dataAbertura: '2024-01-20',
    dataCriacao: '2024-01-20',
    dataAtualizacao: '2024-01-20',
  },
];

export const mockMarcas: Marca[] = [
  {
    id: '1',
    nome: 'Bosch',
    dataCriacao: '2023-01-01',
    dataAtualizacao: '2023-01-01',
  },
  {
    id: '2',
    nome: 'Fras-le',
    dataCriacao: '2023-01-01',
    dataAtualizacao: '2023-01-01',
  },
  {
    id: '3',
    nome: 'Cofap',
    dataCriacao: '2023-01-01',
    dataAtualizacao: '2023-01-01',
  },
];

export const mockCategorias: Categoria[] = [
  {
    id: '1',
    nome: 'Filtros',
    dataCriacao: '2023-01-01',
    dataAtualizacao: '2023-01-01',
  },
  {
    id: '2',
    nome: 'Freios',
    dataCriacao: '2023-01-01',
    dataAtualizacao: '2023-01-01',
  },
  {
    id: '3',
    nome: 'Suspensão',
    dataCriacao: '2023-01-01',
    dataAtualizacao: '2023-01-01',
  },
];

export const mockTiposVeiculo: TipoVeiculo[] = [
  {
    id: '1',
    nome: 'Sedan',
    observacao: 'Carro de passeio com 4 portas',
    dataCriacao: '2023-01-01',
    dataAtualizacao: '2023-01-01',
  },
  {
    id: '2',
    nome: 'SUV',
    observacao: 'Veículo utilitário esportivo',
    dataCriacao: '2023-01-01',
    dataAtualizacao: '2023-01-01',
  },
  {
    id: '3',
    nome: 'Hatchback',
    observacao: 'Carro compacto com porta traseira',
    dataCriacao: '2023-01-01',
    dataAtualizacao: '2023-01-01',
  },
];


export const mockUsuarios: Usuario[] = [
  {
    id: '1',
    nome: 'João Silva',
    email: 'joao.silva@example.com',
    perfil: 'Administrador',
    status: 'Ativo',
    dataCriacao: '2023-01-15',
    dataAtualizacao: '2024-01-15',
  },
  {
    id: '2',
    nome: 'Maria Santos',
    email: 'maria.santos@example.com',
    perfil: 'Supervisor',
    status: 'Ativo',
    dataCriacao: '2023-02-20',
    dataAtualizacao: '2024-01-10',
  },
  {
    id: '3',
    nome: 'Carlos Oliveira',
    email: 'carlos.oliveira@example.com',
    perfil: 'Padrão',
    status: 'Ativo',
    dataCriacao: '2023-03-10',
    dataAtualizacao: '2024-01-05',
  },
  {
    id: '4',
    nome: 'Ana Costa',
    email: 'ana.costa@example.com',
    perfil: 'Supervisor',
    status: 'Inativo',
    dataCriacao: '2023-04-05',
    dataAtualizacao: '2023-12-20',
  },
  {
    id: '5',
    nome: 'Pedro Ferreira',
    email: 'pedro.ferreira@example.com',
    perfil: 'Padrão',
    status: 'Ativo',
    dataCriacao: '2023-05-12',
    dataAtualizacao: '2024-01-08',
  },
];
