export const PERMISSIONS = {
  CLIENTES: {
    VIEW: "CLIENTES_VISUALIZAR",
    CREATE: "CLIENTES_CRIAR",
    EDIT: "CLIENTES_EDITAR",
    DELETE: "CLIENTES_EXCLUIR",
  },
  VEICULOS: {
    VIEW: "VEICULOS_VISUALIZAR",
    CREATE: "VEICULOS_CRIAR",
    EDIT: "VEICULOS_EDITAR",
    DELETE: "VEICULOS_EXCLUIR",
  },
  OS: {
    VIEW: "OS_VISUALIZAR",
    CREATE: "OS_CRIAR",
    EDIT: "OS_EDITAR",
    DELETE: "OS_EXCLUIR",
  },
  PRODUTOS: {
    VIEW: "PRODUTOS_VISUALIZAR",
    CREATE: "PRODUTOS_CRIAR",
    EDIT: "PRODUTOS_EDITAR",
    DELETE: "PRODUTOS_EXCLUIR",
  },
  USUARIOS: {
    VIEW: "USUARIOS_VISUALIZAR",
    CREATE: "USUARIOS_CRIAR",
    EDIT: "USUARIOS_EDITAR",
    DELETE: "USUARIOS_EXCLUIR",
  },
  RELATORIOS: {
    VIEW: "RELATORIOS_VISUALIZAR",
  },
  CONFIG: {
    VIEW: "CONFIG_VISUALIZAR",
    EDIT: "CONFIG_EDITAR",
  },
} as const;
